### ISSUE TITLE
bug: DDI/AMPCD controller PCB: CPL with DIP socket and IRFB320

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#1008]
### Summary:
The DIP-24 socket and the IRFB320 are in BOM and CPL, although the through-hole parts are supposed to be soldered manually.

### Expected Results/How It Should Work:
No through-hole parts in CPL.

### Category:
- [x] ECAD (PCB Design or other electrical hardware)
### Type:
*Check one item.*
- [x] Bug
### Applicable End Item:
*Check one item.*
- [x] Top Level Assembly          

### Associated Filename(s):
OHC0015-10

**Comment by Arribe** [comment]
Through hole parts are an option to have JLCPCB install, but they have generally been cheaper just to do manually.  The last ALE order I placed I had JLC install the Molex connectors because it was way cheaper than buying the connectors from Digikey or Mouser and doing it myself.  The other through hole parts weren't cost effective, or in stock.  Having the through hole parts in the BOM / CPL at least gives the option to have them installed, if one doesn't want them installed then one can choose the don't place part option.

**Comment by Higgins-OH** [comment]
Sounds reasonable, but in this case all the through-hole parts should be in the CPLs. ALE was the first and only I noticed so far.

**Comment by kbastronomics** [comment]
Totally agree. 
Have them in the bom and cpl files

**Comment by jrsteensen** [comment]
Part of #719 for functional PCBs.
