### ISSUE TITLE
Check ABSIS functionality

### ISSUE THREAD

**Issue by balzreber** [jrsteensen/OpenHornet#119]
Full functionality check of both the ABSIS MEGA and ABSIS NANO boards.

**Comment by petersawka** [comment]
ABSIS Nano Board Tested for USB Communication to PC for code Loading:
![image](https://user-images.githubusercontent.com/1192511/107859748-64768680-6df0-11eb-8760-3a5798ab2a4c.png)

Encountered an issue with USB Cable and BUS-OUT Molex Connector:
![image](https://user-images.githubusercontent.com/1192511/107859769-8ff97100-6df0-11eb-9092-681bf99dba7e.png)

Additional tests are required for Nano Programming when not installed at EOL.

**Comment by jrsteensen** [comment]
So, the USB connector vs MOLEX connector interference would be easily fixed using a slimline usb connector or a 90* adapter.

The simplest solution, and I would like to get input here to solve both issues is rather than use JP1, go ahead and disconnect the nano/mega from the ABSIS PCB for programming.

What are your thoughts? @petersawka @L-Walker @amanuense

**Comment by petersawka** [comment]
@jrsteensen I personally am all for removing the Nano for programming; I think this solves both issues, and in some locations in the pit it would more beneficial.

**Comment by jrsteensen** [comment]
To summarize: JP1 does not function as expected. Current workaround will be to remove the Nano from the PCB for programming until PCB is revised at some point in the future. Bumping this to a beta3 issue, since it is not a limiting factor.
