### ISSUE TITLE
UIP Release Package

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#133]
- [x] Update all knobs (shaft cavity and set screws).
    - [x] UFC Assy
    - [x] HUD Panel
    - [x] SPIN RCVY Panel
    - [x] DDI Assy
- [x] Replace all EVU-F2MFL3B14 pots with P0915N-FC20BR10K pot.
    - [x] UFC Assy
    - [x] HUD Panel
- [x] Ensure all CNC'd parts have internal radii at corners.
- [x] Complete all outstanding items assigned in end item project.
- [x] Add all controller PCBs to MCAD.
- [x] Update interconnect diagram.
- [x] Complete top level drawing.
- [x] Update lower subassembly drawings to include setscrews.
- [x] Update OH1A2A drawing to include paint diagram.
- [x] Update OH1A3A drawing to include paint diagram.
- [x] Update OH1A4A drawing to include paint diagram.
- [x] Update OH1A5A drawing to include paint diagram.
- [x] Update OH1A6A drawing to include paint diagram.
- [x] Update OH1A7A drawing to include paint diagram.
- [x] Update OH1A8A drawing to include paint diagram.
- [x] Check for duplicate hardware.

**Comment by jrsteensen** [comment]
fe689c469882230ef77310b0683da36bab09177e
7b1a562724e2b9bba09d5e14d232d1bc7f32341d
1262a5e80fb313d61c9bef36877d5e6475fc3a96

**Comment by jrsteensen** [comment]
f116ba5 - Completed draft of top level drawing. Requires review before proceeding.

[UIP Drawing](https://github.com/jrsteensen/OpenHornet/blob/MCAD_UIP_Release_Package/release/2_Upper%20Instrument%20Panel/OH1A%20-%20ASSY%2C%20UPPER%20INSTRUMENT%20PANEL.PDF)

**Comment by ajmilner85** [comment]
Is the asymmetric installation of the threaded inserts, item 64, into UIP LEFT OUTBOARD LONGERON (Sheet 4/C8) and UIP RIGHT OUTBOARD LONGERON (Sheet 4/B5) intentional or was one omitted by mistake? 

I also can't find where the remaining 6 out of the total 14 8-32 threaded inserts are consumed during the assembly. Are there meant to be 3 inserted into the front and back of each longeron?
