### ISSUE TITLE
Identify 2-layer vs 4-layer PCBs in manufacturing files

### ISSUE THREAD

**Issue by jrsteensen** [jrsteensen/OpenHornet#430]

**Comment by Exprezz0** [comment]
Fixed with #592 
ABSIS_PSU and ABSIS_Backlight Controller are the only ones I'm aware of that require special instructions.  I've also added additional instructions to other PCBs that only have 1-side of components to remind users not to panic if they don't see two BOM's.
![image](https://user-images.githubusercontent.com/81926396/215653414-19755422-8720-4444-b70a-0288c2f5ef55.png)
![image](https://user-images.githubusercontent.com/81926396/215653461-5283597c-8f96-4cb7-a71f-3ba36dc21621.png)

**Comment by Exprezz0** [comment]
Fixed and verified.  Will be implemented in #592
