### ISSUE TITLE
Landing Gear Lever: No LED in Lollipop

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#583]
### Summary:
No LED in Lollipop.

### Expected Results/How It Should Work:
There should be something to illuminate it.

### Screenshots:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/62520296/198686135-1c22cd2f-96a0-4c7d-b2e3-9e3cd03ea019.png">

### Category:
*Check one or more items.*
- [X] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [X] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [X] Left Console
- [ ] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
*Insert assembly or part file names here, i.e. 123456.sldasm, etc.*

**Comment by jrsteensen** [comment]
Fixed in LC v127

![Image](https://user-images.githubusercontent.com/2449496/227680120-34f32499-4893-47ac-9b85-2839c271af82.png)

![Image](https://user-images.githubusercontent.com/2449496/227680168-1352390d-decf-4c41-8634-af27d2974463.png)

![Image](https://user-images.githubusercontent.com/2449496/227680459-8a77dda9-04af-40a3-879c-0843589b91f6.png)
