### ISSUE TITLE
OH5A2A7-12 PCB, LDG CHKLST: Different name in ECAD

### ISSUE THREAD

**Issue by Higgins-OH** [jrsteensen/OpenHornet#589]
*Please fill out the issue as completely as possible. Be very specific and take your time. The more effort you put in to fill the issue out completely, the quicker we can fix this or look at adding your requested feature.*

### Summary:
OH5A2A7-12 is called "PCB, LDG CHKLST" in the Fusion model. On ECAD it's called "LDG_Wing_Fold_PCB_V2"

### Expected Results/How It Should Work:
Same/similar name.

## More Information
*Add an "X" in the square brackets to check the applicable checkboxs.*
### Category:
*Check one or more items.*
- [x] MCAD (SolidWorks)
- [ ] ECAD (PCB Design or other electrical hardware)
- [ ] Software - Sketch
- [ ] Software - DCS-BIOS
- [ ] Software - Library
### Type:
*Check one item.*
- [x] Bug
- [ ] Feature Enhancement
- [ ] Maintenance
- [ ] Question
- [ ] Documentation
### Applicable End Item:
*Check one item.*
- [ ] Top Level Assembly          
- [ ] Lower Instrument Panel (LIP)
- [ ] Main Instrument Panel (MIP)
- [ ] Left Console
- [x] Right Console
- [ ] Seat
- [ ] Center Tub
- [ ] Flight Stick
- [ ] Throttle
- [ ] General Software
### Associated Filename(s):
OH5A2A7-12

**Comment by Exprezz0** [comment]
Fixed with Transition ( Issue #592 ).  Entire directory is being cleaned and fixed, STEP files have been updated and will continue as necessary.  Nomenclature in Fusion 360 will be fixed and match accordingly.  The use of delimiters work within Fusion360 but aren't practical with KiCad 6 because when PCB manufacturing files are generated, they adopted any delimiters and currently, JLC doesn't accept files that have those characters associated with the file name.  

But the new ECAD structure should be understandable and easy to work if you're trying to compare files (ECAD & MCAD)
