### ISSUE TITLE
[Bug]: The Rev 4 Function Select Panel places 2 DNC Resistors

### ISSUE THREAD

**Issue by kbastronomics** [jrsteensen/OpenHornet#971]
### Discord Username

smgvbest (aka Sandra)

### Bug Summary

When ordering the first test run of the Rev4 Function select I noticed the 2 4K7 IC2 resistors where placed on all the boards.   These resistors are for stand alone troubleshoot and should not be placed   they are marked Do Not Place (DNP) on the schematic however both the BOM and CPL files had them so they were placed

Under normal circumstances, these resistors should not be placed

### Expected Results

JCLPCB should not have placed the resistors

### Actual Results

The Resistors were placed on all boards ordedred.

### Screenshots/Images/Files

![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/1d925537-c192-4a3c-b548-ea9a351fefe1)
![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/31fe431a-9453-4b00-bf7b-137237f2f933)

### Applicable Part Numbers

UFC_Function Select

### Release Version

1.0.0-beta.1

### Category

Electrical (PCBs/Wiring/etc)

### Applicable End Item(s)

Upper Instrument Panel (UIP)

### Built to print?

- [X] I built (or attempted to build) the part to the OpenHornet print without any deviations.
- [ ] I am not building this part to the OH print. (List deviations in detail in the Miscellaneous Info text area below.)

**Comment by Exprezz0** [comment]
I took a look at this and I'm finding some discrepancies with the version that's currently in the GitHub repo and the version you posting as having an issue.  The current schematic for UFC_Function Select is showing as revision 2.  Keep in mind, I haven't been able to go through the functional stuff yet so I know it wasn't updated recently.  That being said, on the schematic, I'm only seeing 2x resistors (R1 and R4; 33 and 10k respectively).  There are no 4.7k resistors in the schematic.  

![image](https://github.com/jrsteensen/OpenHornet/assets/81926396/50f5d500-6ee1-4dd6-bc47-ae54cf3f97ed)

I looked at the PCB because I figured that it was probably a mismatch between the schematic and the board.  But again, I'm only seeing 2 resistors (R1 and R4; same values)

![image](https://github.com/jrsteensen/OpenHornet/assets/81926396/cb057d1d-9f6d-47bf-be32-904209451815)
![image](https://github.com/jrsteensen/OpenHornet/assets/81926396/7cff446e-29fa-4c5f-9b7a-8ddf98ad40af)

_(ignore the missing switches.  I haven't updated the paths, therefore they wouldn't render)_

The picture you posted of the UFC Function Select looks to be from an older version.

**Comment by kbastronomics** [comment]
The Rev4 PCB is a special build not yet commited to the github.   John wanted this issue created so he could make the needed updates,   We didn't want this build as part of the beta1 github yet until we proved it out will be beta1 once john promotes promotes the files

this is the new board

![image](https://github.com/jrsteensen/OpenHornet/assets/19305697/0b10a47e-76a5-40a8-a6ea-d76d897822bd)

**Comment by jrsteensen** [comment]
No, its on github, just on the v1.0.0-beta1_experimental_ufc_ws2812b branch.

**Comment by jrsteensen** [comment]
Fixed with 29a55098f0a2560070b0ed115b2a45cc64700cf9
